
const CELEBS_INFO_URL = null
const FETCH_CELEBS = 'FETCH_CELEBS'
const FETCH_CELEB = 'FETCH_CELEB'
const FETCH_CELEBS_ERROR = 'FETCH_CELEBS_ERROR'
const FETCH_CELEB_ERROR = 'FETCH_CELEB_ERROR'

export {
  CELEBS_INFO_URL,
  FETCH_CELEBS,
  FETCH_CELEB,
  FETCH_CELEBS_ERROR,
  FETCH_CELEB_ERROR
}
